# Generated by Django 3.2.9 on 2021-12-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211222_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, default='RU', max_length=10, verbose_name='язык'),
        ),
    ]
